# Cache downloaded dependencies and plugins between builds.
# Not strictly necessary, but speeds up the builds.
cache:
  key: "$CI_JOB_NAME"
  paths:
    # Must be within the repository under test hence we can't use the
    # default ~/.m2
    - .m2/repository
variables:
  # Use the cached directory above.
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

deploy:
  image: maven:3.6.1-jdk-11 # docker image with Maven
  before_script:
    - chmod 400 $CI_SSH_KEY
    - . ci/setup-mvn-proxy.sh
    

  script:
    - cd /builds/p1809208/mif03_tp/serverMVC
    - mvn clean && mvn package 
    - scp -o StrictHostKeyChecking=no -i $CI_SSH_KEY /builds/p1809208/mif03_tp/serverMVC/target/server.war gitlabci@192.168.75.70:/opt/tomcat/webapps/v2.war

